version: '3'

services:
  db:
    image: postgres:9.5
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/onebitexchange
      - gems:/gems
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  postgres:
  gems:
